# Server configuratiom

[NETWORK]
# What address should be used for listening? 0.0.0.0 for the IP address of all interfaces.
listen_address=192.168.1.2

# Which port to listen
listen_port=25565

# How many connections?
max_connections=100

# How many time to close a non-iteractive connection? IN SECONDS
connection_timeout=150

[DATABASE]

MAX_SIZE=1024
DatabasePath=/var/lib/tcpserver/credentials.json

[LOGS]
# Where the log will be written 
LogPath=/var/log/tcpserver/log.txt
#If an error occurs with the Logging system, DO YOU WISH TO CONTINUE WITHOUT IT?
Run_Without_loggin=false

[PROCESS]
# Strorage the pid process of the service.
pid_file=/run/tcpserver.pid
